# Generated by Django 3.2.8 on 2021-10-07 10:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 10, 7, 15, 51, 2, 129323))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 10, 7, 15, 51, 2, 129323))),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(default=None, max_length=40)),
                ('updated_by', models.CharField(default=None, max_length=40)),
                ('brand', models.CharField(max_length=50)),
                ('modelName', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=10, max_digits=10)),
                ('user', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='cars')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 10, 7, 15, 51, 2, 129323))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 10, 7, 15, 51, 2, 129323))),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(default=None, max_length=40)),
                ('updated_by', models.CharField(default=None, max_length=40)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 10, 7, 15, 51, 2, 129323))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 10, 7, 15, 51, 2, 129323))),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(default=None, max_length=40)),
                ('updated_by', models.CharField(default=None, max_length=40)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 10, 7, 15, 51, 2, 129323))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 10, 7, 15, 51, 2, 129323))),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(default=None, max_length=40)),
                ('updated_by', models.CharField(default=None, max_length=40)),
                ('orderDateFrom', models.DateTimeField(default=datetime.datetime(2021, 10, 7, 15, 51, 2, 132329))),
                ('orderDateExpire', models.DateTimeField(default=datetime.datetime(2021, 10, 7, 16, 51, 2, 132329))),
                ('totalOrderCost', models.DecimalField(decimal_places=10, max_digits=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carhub.car')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carhub.category'),
        ),
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carhub.city'),
        ),
    ]
