# Generated by Django 3.2.8 on 2021-10-09 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 9, 20, 26, 20, 925301)),
        ),
        migrations.AlterField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 9, 20, 26, 20, 925301)),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 9, 20, 26, 20, 925301)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 9, 20, 26, 20, 925301)),
        ),
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 9, 20, 26, 20, 925301)),
        ),
        migrations.AlterField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 9, 20, 26, 20, 925301)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 9, 20, 26, 20, 925301)),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDateExpire',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 9, 21, 26, 20, 927341)),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDateFrom',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 9, 20, 26, 20, 927341)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 9, 20, 26, 20, 925301)),
        ),
    ]
