# Generated by Django 3.2.8 on 2021-10-18 12:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carhub', '0002_auto_20211009_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 18, 10, 9, 736946)),
        ),
        migrations.AlterField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 18, 10, 9, 736946)),
        ),
        migrations.AlterField(
            model_name='car',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 18, 10, 9, 736946)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 18, 10, 9, 736946)),
        ),
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 18, 10, 9, 736946)),
        ),
        migrations.AlterField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 18, 10, 9, 736946)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 18, 10, 9, 736946)),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDateExpire',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 19, 10, 9, 739944)),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDateFrom',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 18, 10, 9, 739944)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 18, 10, 9, 736946)),
        ),
    ]
