# Generated by Django 3.2.8 on 2021-10-19 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carhub', '0004_auto_20211018_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 19, 10, 49, 25, 256765)),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 19, 10, 49, 25, 256765)),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 19, 10, 49, 25, 256765)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 19, 10, 49, 25, 256765)),
        ),
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 19, 10, 49, 25, 256765)),
        ),
        migrations.AlterField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 19, 10, 49, 25, 256765)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 19, 10, 49, 25, 256765)),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDateExpire',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 19, 11, 49, 25, 260911)),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDateFrom',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 19, 10, 49, 25, 260911)),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalOrderCost',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 19, 10, 49, 25, 256765)),
        ),
    ]
