# Generated by Django 3.2.8 on 2021-10-20 10:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carhub', '0007_auto_20211019_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_detail', to='carhub.car'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 20, 15, 51, 11, 226274)),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(upload_to='cars'),
        ),
        migrations.AlterField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 20, 15, 51, 11, 226274)),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 20, 15, 51, 11, 226274)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 20, 15, 51, 11, 226274)),
        ),
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 20, 15, 51, 11, 226274)),
        ),
        migrations.AlterField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 20, 15, 51, 11, 226274)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 20, 15, 51, 11, 226274)),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDateExpire',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 20, 16, 51, 11, 228280)),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDateFrom',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 20, 15, 51, 11, 228280)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 20, 15, 51, 11, 226274)),
        ),
    ]
