# Generated by Django 3.2.8 on 2021-10-21 07:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carhub', '0008_auto_20211020_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('BKD', 'Booked'), ('CAN', 'Cancelled'), ('COM', 'Completed')], default='BKD', max_length=3),
        ),
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 12, 33, 56, 566284)),
        ),
        migrations.AlterField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 12, 33, 56, 566284)),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 12, 33, 56, 566284)),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 12, 33, 56, 566284)),
        ),
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 12, 33, 56, 566284)),
        ),
        migrations.AlterField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 12, 33, 56, 566284)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 12, 33, 56, 566284)),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDateExpire',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 13, 33, 56, 566284)),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDateFrom',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 12, 33, 56, 566284)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 12, 33, 56, 566284)),
        ),
        migrations.CreateModel(
            name='UserProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 10, 21, 12, 33, 56, 566284))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 10, 21, 12, 33, 56, 566284))),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(default=None, max_length=40)),
                ('updated_by', models.CharField(default=None, max_length=40)),
                ('is_validated', models.BooleanField(default=False)),
                ('dl', models.ImageField(upload_to='dl')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
